SCAL-139 allowance for inner with blocks
prolific-oss/mongoengine pull request #8
Opened 2021-04-14 15:14 UTC by iguanaonmystack

This branch add use_existing=False to the run_in_transaction class that was added in the SCAL-104 branch.

2021-04-15 08:33 UTC, jonasanso reviewed
Code looks good, please add some tests.

2021-04-19 10:21 UTC, iguanaonmystack commented on mongoengine/context_managers.py
>          return self.session
@jonasanso is there any particular reason this returns `self.session` rather than just `self`? Doing so would mean the clunky `runner1 = run_in_transaction(); with runner1: ...` in the tests could be written a bit less clunky way as `with run_in_transaction() as runner1: ...`

2021-04-19 10:24 UTC, jonasanso commented on mongoengine/context_managers.py
>          return self.session
Initially i though it would be nice to be able to do somthing like
```
with run_in_transaction() as session: 
     session.commit()
```
I am happy with returning self or returning the transaction or anything you like.

2021-04-19 10:24 UTC, jonasanso approved these changes

2021-04-19 13:35 UTC, jonasanso requested changes
Please update the docs in the class the part that says `as session` 
I think there is also a notion page we might need to update

2021-04-19 14:13 UTC, jonasanso approved these changes

2022-01-13 09:24 UTC, closed without merging